### ISSUE TITLE
Dialog (feature request)

### ISSUE THREAD

**Issue by kalatchev** [aleversn/VFluent#4]
Hi again,

here is my second proposal - **dialog**. And here's what I have in UWP:

![image](https://user-images.githubusercontent.com/10154711/83144552-2e776200-a0fc-11ea-8980-0734b214b76f.png)

**Comment by aleversn** [comment]
Thanks for ur suggestion, we will update it soon, and u can currently try the `InfoBox` component.

**Comment by aleversn** [comment]
We have updated the InfoBox component to the new Windows 11 style in `v0.1.90`; this issue will be closed.
